<a href="https://colab.research.google.com/github/Aashi230/numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**3)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[ 1  8 27]


In [ ]:
print(np.power(a,2)) #for n exponent

[1 4 9]


In [ ]:
print(np.sqrt(a)) #to find the sq root

[1.         1.41421356 1.73205081]


In [ ]:
arr=np.array([10,20,20,30,40,50]) #defining 2d array
print(np.mean(arr))
print(np.median(arr))

28.333333333333332
25.0


In [ ]:
print(np.max(arr))
print (np.min(arr))
print(np.sum(arr))
print(np.std(arr)) #standard deviation
print(np.var(arr)) #variance

50
10
170
13.43709624716425
180.55555555555557


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,11) #array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.rand(5) #gives a random below 1

array([0.77631267, 0.79169813, 0.33119759, 0.32662195, 0.90019164])

In [ ]:
np.random.randint(1,100,10) #give random integers

array([68, 98, 82, 72, 30, 38, 53, 73, 29, 48])

In [ ]:
arr=np.array([5,2,9,1])
print(np.sort(arr))

[1 2 5 9]


In [ ]:
arr=np.array([1,2,2,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [ ]:
arr= np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]
